apiVersion: apps/v1
kind: Deployment
metadata:
    name: nim-calculator-deployment
    labels:
        app: nim-calculator-deployment
spec:
    replicas: 2
    revisionHistoryLimit: 0
    selector:
        matchLabels:
            app: nim-calculator-image
    template:
        metadata:
            labels:
                app: nim-calculator-image
        spec:
            containers:
                - name: nim-calculator-image
                  image: alexandrebo/nim-calculator:latest
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nim-calculator-service
spec:
    type: NodePort
    selector:
        app: nim-calculator-image
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30666
